# generated by fastapi-codegen:
#   filename:  openapi.yml
#   timestamp: 2023-03-11T23:56:44+00:00

from __future__ import annotations

from typing import List, Optional
from uuid import UUID

from pydantic import BaseModel, EmailStr, Field, SecretStr


class Address(BaseModel):
    street: str = Field(..., example='Av. Paulista')
    number: str = Field(..., example='1001')
    complement: Optional[str] = Field(None, example='apto 21')
    city: str = Field(..., example='Sao Paulo')
    state: str = Field(..., example='SP')
    zip: str = Field(..., example='01311000')


class BankAccount(BaseModel):
    agency: Optional[str] = Field(None, example='60883')
    accountNumber: Optional[str] = Field(None, example='3413')
    digit: Optional[str] = Field(None, example='1')


class CreditCard(BaseModel):
    code: Optional[str] = Field(None, example='5118598797832798')
    name: Optional[str] = Field(None, example='ARIEL S DOS SANTOS')
    expirationDate: Optional[str] = Field(None, example='1994-11-05T08:15:30-05:00')
    verifyingDigits: Optional[str] = Field(None, example='183')


class Service(BaseModel):
    id: UUID = Field(..., example='9cd94d37-3b45-4d66-a4ac-1ee904a87491')
    serviceType: str = Field(..., example='Tosa')
    price: float = Field(..., example=89.9)
    userId: UUID = Field(..., example='9cd94d37-3b45-4d66-a4ac-1ee904a87491')


class Request(BaseModel):
    id: UUID = Field(..., example='9cd94d37-3b45-4d66-a4ac-1ee904a87491')
    userId: UUID = Field(..., example='9cd94d37-3b45-4d66-a4ac-1ee904a87491')
    serviceId: UUID = Field(..., example='9cd94d37-3b45-4d66-a4ac-1ee904a87491')
    date: str = Field(..., example='1994-11-05T08:15:30-05:00')
    status: Optional[str] = Field(None, example='Rejeitado')


class ServiceList(BaseModel):
    data: Optional[List[Service]] = None


class RequestList(BaseModel):
    data: Optional[List[Request]] = None


class UserData(BaseModel):
    firstName: str = Field(..., example='Ariel')
    lastName: str = Field(..., example='Silva dos Santos')
    email: EmailStr = Field(..., example='ariel.silva@ipets.com')
    password: SecretStr
    address: Address
    bankAccount: Optional[BankAccount] = None
    creditCards: Optional[List[CreditCard]] = None
    avatar: Optional[str] = Field(None, example='U3dhZ2dlciByb2Nrcw==')


class ServiceData(BaseModel):
    serviceType: str = Field(..., example='Tosa')
    price: float = Field(..., example=89.9)
    userId: UUID = Field(..., example='9cd94d37-3b45-4d66-a4ac-1ee904a87491')


class RequestData(BaseModel):
    userId: UUID = Field(..., example='9cd94d37-3b45-4d66-a4ac-1ee904a87491')
    serviceId: UUID = Field(..., example='9cd94d37-3b45-4d66-a4ac-1ee904a87491')
    date: str = Field(..., example='1994-11-05T08:15:30-05:00')


class User(BaseModel):
    id: UUID = Field(..., example='9cd94d37-3b45-4d66-a4ac-1ee904a87491')
    code: Optional[str] = Field(None, description='CPF ou CNPJ', example='98202023025')
    firstName: str = Field(..., example='Ariel')
    lastName: str = Field(..., example='Silva dos Santos')
    email: EmailStr = Field(..., example='ariel.silva@ipets.com')
    address: Address
    bankAccount: Optional[BankAccount] = None
    creditCards: Optional[List[CreditCard]] = None
    avatar: Optional[str] = Field(None, example='U3dhZ2dlciByb2Nrcw==')
